SOURCE/MarketingSystem/MarketingSystem/Areas/FrontEnd/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketingSystem.Areas.FrontEnd.Controllers
{
    public class AboutUsController : Controller
    {
        // GET: FrontEnd/AboutUs
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult SearchAboutUS(int Page=1, string Name="")
        {
            try
            {
                return PartialView("_AboutUs", "");
            }
            catch
            {
                return PartialView("_AboutUs", /*new List<ListPostCategory>().ToPagedList(1, 1)*/ "");
            }
        }
    }
}

SOURCE/MarketingSystem/MarketingSystem/Areas/FrontEnd/Controllers/NewsFrontEndController.cs
using APIProject.Controllers;
using Data.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketingSystem.Areas.FrontEnd.Controllers
{
    public class NewsFrontEndController : BaseController
    {
        // GET: FrontEnd/News
        public ActionResult Index()
        {
            ViewBag.ListNews = newsBusiness.ListNewsWeb(3);
            ViewBag.ListCategory = newsBusiness.GetListNewCategory();
            return View();
        }
        public PartialViewResult SearchNewsWeb(int Page = 1, string Name = "" ,int CateNewsID = 0)
        {
            try
            {
                ViewBag.ListNews = newsBusiness.ListNewsWeb(3);
                ViewBag.ListCategory = newsBusiness.GetListNewCategory();
                var data = newsBusiness.SearchNewsWeb(Page, Name, CateNewsID);
                return PartialView("_ListNewsWeb", data);
            }
            catch
            {
                return PartialView("_ListNewsWeb", new List<ListNewsOutputModel>().ToPagedList(1, 1));
            }
        }

        [HttpGet]
        public PartialViewResult NewsDetail(int ID)
        {

            var data = newsBusiness.GetNewsDetail(ID);
            return PartialView("_NewsDetailWeb", data);
        }
    }
}

SOURCE/MarketingSystem/MarketingSystem/Areas/FrontEnd/Controllers/ServicePlanFEController.cs
using APIProject.Controllers;
using Data.Business;
using Data.DB;
using Data.Model;
using Data.Model.APIWeb;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketingSystem.Areas.FrontEnd.Controllers
{
    public class ServicePlanFEController : BaseController
    {
        // GET: FrontEnd/ServicePlanFE
        public ActionResult Index()
        {
            ViewBag.ListCategory = servicePlanBusiness.GetListCategory();
            return View();
        }

        public PartialViewResult SearchService(int Page = 1, string Name = "", int CateID = 0)
        {
            try
            {
                ViewBag.ListCategory = servicePlanBusiness.GetListCategory();
                var data = servicePlanBusiness.SearchFontEnd(Page, Name, 1, CateID);
                return PartialView("_Service", data);
            }
            catch
            {
                return PartialView("_Service", new List<ListServicePlanOutputModel>().ToPagedList(1, 1));
            }
        }

        [HttpGet]
        public PartialViewResult ServiceDetail(int ID)
        {

            var listProvince = customerBusiness.GetListProvince();
            var listDistrict = customerBusiness.GetListDistrict(listProvince.FirstOrDefault().id);
            var listVillage = customerBusiness.GetListVillage(listDistrict.FirstOrDefault().id);
            ViewBag.ListDistrict = listDistrict;
            ViewBag.ListVillage = listVillage;
            ViewBag.LisProvince = listProvince;
            var data = servicePlanBusiness.ServiceDetail(ID);
            return PartialView("_ServiceDetail", data);
        }

        //Đăng ký dịch vụ
        [HttpPost]
        public int CreateOrder(int ServiceID, string Note, int ProvinceID, int DistrictID, int VillageID, string Address)
        {
            if (client == null)
            {
                return -1;
            }
            OrderInputModel input = new OrderInputModel();
            input.ServiceID = ServiceID;
            input.token = client.Token;
            input.Note = Note;
            input.ProvinceID = ProvinceID;
            input.DistrictID = DistrictID;
            input.VillageID = VillageID;
            input.Address = Address;
            var data = orderBusiness.CreateOrder(input);

            return data.Status;
        }

        public ActionResult CusService()
        {
            return View("CusService");
        }

        public PartialViewResult SearchCusService(int Page, string SearchKey, string Code, int? Status, string Fromdate, string Todate)
        {
            try
            {

                if (client != null)
                {
                    var data = customerServicePlan.Myservice(client.Id, Page, SearchKey, Code, Status, Fromdate, Todate);
                    return PartialView("TableCusService", data);
                }
                return PartialView("TableCusService", new List<CustomerService>().ToPagedList(1, 1));

            }
            catch
            {
                return PartialView("TableCusService", new List<CustomerService>().ToPagedList(1, 1));
            }
        }

        [HttpPost]
        public JsonResult CusDelServicePlan(int id)
        {
            return Json(customerServicePlan.CusDelSercicePlan(id), JsonRequestBehavior.AllowGet);
        }
    }
}

SOURCE/MarketingSystem/MarketingSystem/Areas/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">

    <title>NEXUS_System</title>
    <!-- Loading third party fonts -->
    <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:300,400,700" rel="stylesheet" type="text/css">
    @*<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">*@

    <!-- Loading main css file -->
    @*<link rel="stylesheet" href="css/animate.css">*@
    @*<link rel="stylesheet" href="style.css">*@
    @Styles.Render("~/fontend/fonts")
    @Styles.Render("~/fontend/stylecss")
    @Styles.Render("~/fontend/css")
    @Scripts.Render("~/fontend/js")
    @Styles.Render("~/fontend/fonts")
    @Styles.Render("~/fontend/stylecss")
    <!--[if lt IE 9]>
    <script src="js/ie-support/html5.js"></script>
    <script src="js/ie-support/respond.js"></script>
    <![endif]-->

</head>

<body>

    <div id="site-content">

        <header class="site-header">
            <div class="top-header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <a href="tel:80049123441">Call Us: (800) 49123441</a>
                        </div>
                        <div class="col-md-4">
                            @{ var ss = (@Data.Model.APIWeb.LoginOutputModel)HttpContext.Current.Session["Client"];
                                if (ss == null)
                                {
                                    <nav class="member-navigation pull-right">
                                        <a href="@Url.Action("Register","/HomeFrontEnd")"><i class="fa fa-user"></i> Register</a>
                                        <a href="@Url.Action("Login","/HomeFrontEnd")"><i class="fa fa-lock"></i> Login</a>
                                    </nav> }
                                else
                                {
                                    <div class="dropdown pull-right">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            @(ss.Name)
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="dropdown-item" href="@Url.Action("CusService","/ServicePlanFE")">Dịch vụ sở hữu</a>
                                            <a class="dropdown-item" href="@Url.Action("CusDetail","/HomeFrontEnd")">Tài khoản</a>
                                            <a class="dropdown-item" href="javascript:void(0)" onclick="showchangePass()">Đổi mật khẩu</a>
                                            <a class="dropdown-item" href="javascript:void(0)" onclick="logoutweb();">@*<i class="fa fa-sign-out" style="padding-right:10px"></i>*@Đăng xuất</a>
                                        </div>
                                    </div> } }

                        </div>
                    </div>

                </div> <!-- .container -->
            </div> <!-- .top-header -->

            <div class="bottom-header">
                <div class="container">

                    <a href="@Url.Action("Index","/HomeFrontEnd")" class="branding pull-left">
                        <img src="~/Content/font_end/images/logo-footer.png" alt="Site title" class="logo-icon">
                        <h1 class="site-title">Nexus</h1>
                        <h2 class="site-description">Quickly connecting the world.</h2>
                    </a> <!-- #branding -->

                    <nav class="main-navigation pull-right">
                        <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
                        <ul class="menu">
                            @*<li class="menu-item"><a href="news.html">News</a></li>*@
                            <li class="menu-item">@Html.ActionLink("Tin tức", "Index", "NewsFrontEnd")</li>
                            <li class="menu-item">@Html.ActionLink("Về chúng tôi", "Index", "AboutUs")</li>
                            <li class="menu-item">@Html.ActionLink("Dịch vụ", "Index", "ServicePlanFE")</li>
                            <li class="menu-item">@Html.ActionLink("Contact", "Index", "Contact")</li>
                        </ul>
                    </nav> <!-- .main-navigation -->
                </div> <!-- .container -->
            </div> <!-- .bottom-header -->
        </header> <!-- .site-header -->

        <main class="content" style="height:100vh; display:inline-block;width:100%;">
            @RenderBody()
        </main> <!-- .content -->

        <footer class="site-footer wow fadeInUp">
            <div class="container">

        <div class="row">
            <div class="col-md-6">

                <div class=" branding">
                    <img src="~/Content/font_end/images/logo-footer.png" alt="Site title" class="logo-icon">
                    <h1 class="site-title"><a href="#">Nexus</a></h1>
                    <h2 class="site-description">Quickly connecting the world.</h2>
                </div> <!-- .branding -->

                <p class="copy">Copyright 2014 NEXUS. designed by Themezy. All rights reserved</p>
            </div>

            <div class="col-md-6 align-right">

                <nav class="footer-navigation">
                    <a href="@Url.Action("Index","/NewsFrontEnd")">Tin tức</a>
                    <a href="@Url.Action("Index","/AboutUs")">Về chúng tôi</a>
                    <a href="@Url.Action("Index","/ServicePlanFE")">Dịch vụ</a>
                    <a href="@Url.Action("Index","/Contact")">Contact</a>
                </nav> <!-- .footer-navigation -->

                <div class="social-links">
                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
                    <a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a>
                </div> <!-- .social-links -->

            </div>
        </div>

    </div>
</footer> <!-- .site-footer -->

    </div> <!-- #site-content -->
    @*<script src="js/jquery-1.11.1.min.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/app.js"></script>*@

    @*// modal đổi mật khẩu*@
    <div id="changePassword" class="modal fade" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><i class="fa fa-lock" aria-hidden="false"></i> Thay đổi mật khẩu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <label>Mật khẩu hiện tại</label>
                            <input class="form-control" type="password" id="txtCurrentPassword" />
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-12 col-sm-12 col-12">
                            <label>Mật khẩu mới</label>
                            <input class="form-control" type="password" id="txtNewPassword" />
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-12 col-sm-12 col-12">
                            <label>Xác nhận mật khẩu mới</label>
                            <input class="form-control" type="password" id="txtConfirmPassword" />
                            <i class="iconChangePassword text-success fa fa-check"></i>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Đóng</button>
                    <button type="button" class="btn btn-primary" onclick="changePassword()">Thay đổi</button>
                </div>
            </div>
        </div>
    </div>

</body>

</html>



@* model load *@
<!--<div class="modal" id="modalLoad" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
        <div class="modal-content text-center py-3">
            <div class="modal-body text-center">
                <i class="fa fa-spinner text-success fa-spin" style="font-size: 40px;"></i>
                <div class="col-md-12 text-center mt-2">
                    <span>Đang xử lý</span>
                </div>
            </div>
        </div>
    </div>
</div>-->

<script type="text/javascript">
    function logoutweb() {
        if (!navigator.onLine) {
            swal({
                title: "Kiểm tra kết nối internet!",
                text: "",
                icon: "warning"
            })
            return;
        }
        $.ajax({
            url: '/HomeFrontEnd/Logout',
            data: {},
            type: 'POST',
            success: function (response) {
                if (response == 1) {
                    location.reload();
                }
            },
            error: function (result) {
                console.log(result.responseText);
            }
        });
    }
    function showchangePass() {
        $('#changePassword').modal('show');
    }

    //đổi mật khẩu
    function changePassword() {
        if (!navigator.onLine) {
            swal({
                title: "Kiểm tra kết nối internet!",
                text: "",
                icon: "warning"
            })
            return;
        }
        var currentPassword = $.trim($("#txtCurrentPassword").val());
        var newPassword = $.trim($("#txtNewPassword").val());
        var confirmPassword = $.trim($("#txtConfirmPassword").val());

        if (currentPassword == "" || newPassword == "" || confirmPassword == "") {
            swal({
                title: "Vui lòng nhập đầy đủ!",
                text: "",
                icon: "warning"
            })
            return;
        }
        if (newPassword != confirmPassword) {
            $("#txtConfirmPassword").val("");
            swal({
                title: "Mật khẩu xác nhận không đúng",
                text: "",
                icon: "warning"
            })
            return;
        }

        $.ajax({
            url: '/HomeFrontEnd/ChangePassword',
            type: 'POST',
            data: {
                CurrentPassword: currentPassword,
                NewPassword: newPassword
            },
            type: 'POST',
            success: function (response) {
                if (response == 1) {
                    $("#changePassword").modal("hide");
                    swal({
                        title: "Đổi mật khẩu thành công",
                        text: "",
                        icon: "success"
                    })
                } else
                    if (response == 2) {
                        $("#txtCurrentPassword").val("");
                        swal({
                            title: "Mật khẩu cũ không đúng",
                            text: "",
                            icon: "warning"
                        })
                    } else {
                        swal({
                            title: "Không thể đổi mật khẩu",
                            text: "",
                            icon: "warning"
                        })
                    }
            },
            error: function (result) {
                console.log(result.responseText);
                swal({
                    title: "Có lỗi",
                    text: "",
                    icon: "warning"
                })
            }
        });
    }

</script>