SOURCE/MarketingSystem/MarketingSystem/Controllers/ServicePlanController.cs
using APIProject.App_Start;
using APIProject.Controllers;
using System;
using Data.Model;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarketingSystem.Controllers
{
    public class ServicePlanController : BaseController
    {
        // GET: ServicePlan
        [UserAuthenticationFilter]
        public ActionResult Index()
        {
            //Lấy danh sách danh mục
            ViewBag.listCate = servicePlanBusiness.GetListCategory();
            return View();
        }
        //Tìm kiếm thông tin gói cước
        [HttpGet]

        public PartialViewResult Search(int page, string searchKey, Boolean? status, int? cateID, string fromDate, string toDate)
        {
            ViewBag.searchKey = searchKey;
            ViewBag.status = status;
            ViewBag.cateID = cateID;
            ViewBag.fromDate = fromDate;
            ViewBag.toDate = toDate;
            //Lấy danh sách danh mục
            ViewBag.listCate = servicePlanBusiness.GetListCategory();
            return PartialView("_TableServicePlan", servicePlanBusiness.Search(page, searchKey, status, cateID, fromDate, toDate));
        }


        //Thêm mới gói cước
        [HttpPost]
        public JsonResult AddServicePlan(ListServicePlanOutputModel input)
        {
            return Json(servicePlanBusiness.AddServicePlan(input), JsonRequestBehavior.AllowGet);
        }

        //Cập nhật thông tin gói cước
        [HttpPost]
        public JsonResult UpdateServicePlan(ListServicePlanOutputModel input)
        {
            return Json(servicePlanBusiness.UpdateServicePlan(input), JsonRequestBehavior.AllowGet);
        }

        //Xóa gói cước
        public JsonResult DelServicePlan(int id)
        {
            return Json(servicePlanBusiness.DelSercicePlan(id), JsonRequestBehavior.AllowGet);
        }
    }
}

SOURCE/MarketingSystem/MarketingSystem/Views/ServicePlan/Index.cshtml
@using Data.Utils;
@using Data.Model;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12 mt-5">
    <div class="breadcrumb-holder">
        <div class="row pb-3 pt-3">
            <div class="text-dark">
                <h4><i class="fa fa-mobile-phone"></i> Quản lý gói cước</h4>
            </div>
        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col-md-4 col-12 mt-1">
        <input id="txt-search-key" class="form-control" placeholder="Nhập tên gói cước" />
    </div>
    <div class="col-md-4 col-12 mt-1">
        <input type="text" class="form-control relative-icon-calendar date" id="txt-from-date" placeholder="Từ ngày" />
        <i class="fa fa-calendar absolute-icon-calendar"></i>
    </div>
    <div class="col-md-4 col-12 mt-1">
        <input type="text" class="form-control relative-icon-calendar date" id="txt-to-date" placeholder="Đến ngày" />
        <i class="fa fa-calendar absolute-icon-calendar"></i>
    </div>
    <div class="col-md-4 col-12 mt-1">
        <select class="form-control" id="status-value-search">
            <option selected disabled hidden>--Trạng thái--</option>
            <option value="2">Tất cả</option>
            <option value="1">Hoạt động</option>
            <option value="0">Ngừng hoạt động</option>
        </select>
    </div>
    <div class="col-md-4 col-12 mt-1">
        <select class="form-control" id="cateID-value-search">
            <option selected disabled hidden>--Danh mục--</option>
            @{
                <option>Tất cả</option>
                foreach (var dt in (List<ListCategoryOutputModel>)ViewBag.listCate)
                {
                    <option value="@dt.ID">@dt.Name</option>
                }
            }
        </select>
    </div>
    <div class="col-md-4 col-12 mt-1 float-right">
        <button class="btn btn-outline-success float-right m-2" data-toggle="modal" data-target="#add-service-plan"><i class="fa fa-plus" aria-hidden="true"></i> Thêm mới</button>
        <button class="btn btn-outline-primary float-right m-2" id="btn-search-service-plan" onclick="SearchServicePlan()"><i class="fa fa-search"></i> Tìm kiếm</button>
    </div>
</div>

<div class="row mt-3">
    <div class="col-12" id="tbl-service-plan">@{Html.RenderAction("Search", "ServicePlan", new { page = 1 });}</div>
</div>


@*Modal thêm gói cước*@
<div class="modal fade" id="add-service-plan" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-white" style="background-color:#1E8449 ">
                <h5 class="modal-title"> <i class="fa fa-plus-square" aria-hidden="true"></i>&nbsp Thêm gói cước</h5>
                <button type="button" class="close " style="color:coral" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="frm-add-service-plan" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Tên gói cước</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <input type="text" name="Name" class="form-control" id="txt-name" placeholder="Nhập tên gói cước..." />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Giá gói cước</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <input type="text" class="form-control number" id="txt-price" placeholder="Nhập giá gói cước..." />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Giá trị trong bao nhiêu tháng</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <input type="number" name="Value" onkeydown="javascript: return event.keyCode == 69 || event.keyCode == 189 || event.keyCode == 190 || event.keyCode == 188 ? false : true" class="form-control number" id="value" placeholder="Nhập giá trị..." />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Danh mục</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <select class="form-control" id="cateID-value-add" name="CateID">
                                @{
                                    foreach (var dt in (List<ListCategoryOutputModel>)ViewBag.listCate)
                                    {
                                        <option value="@dt.ID">@dt.Name</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Trạng thái</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <select class="form-control" id="status-value-add">
                                <option value="1">Hoạt động</option>
                                <option value="0">Ngưng hoạt động</option>
                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Mô tả</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <textarea class="form-control" name="Descreiption" style="height:75px !important" id="txt-description" placeholder="Nhập nội dung mô tả..."></textarea>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Ảnh đại diện</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12 text-center">
                            <a href="" class="text-bold mb-3" style="width:100%;height:100%; color: #5A5A5A;" id="add-img">
                                <img id="tagImg" src="https://cdn4.iconfinder.com/data/icons/social-communication/142/add_photo-512.png" class="col-3" alt="Chọn" />

                            </a>
                            <div class="col-8 offset-2">
                                <div>
                                    <div class="article" id="div-add-img" style="position:relative">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-success" onclick="AddServicePlan()">Thêm mới</button>

            </div>
        </div>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('#status-value-search').change(function () {
            SearchServicePlan();
        })
        $('#cateID-value-search').change(function () {
            SearchServicePlan();
        })
    })
    $(document).on("keyup", function (e) {
        if (e.keyCode == 13) {
            $("#btn-search-service-plan").click();
        }
    });

    $("#add-img").off('click').on('click', function (e) {
        e.preventDefault();
        var fider = new CKFinder();
        fider.selectActionFunction = function (fileUrl) {
            $("#div-add-img").empty();
            $("#div-add-img").append('<div style ="margin-top:10px;"><img id="img-add" class="imgCreateCategory cursor-pointer" width="100%" height="100%" src="' + fileUrl + '" onclick="ChangeImg($(this));" /></div>');
        }
        fider.popup();
    });

    function ChangeImg($url) {
        var fider = new CKFinder();
        fider.selectActionFunction = function (fileUrl) {
            $url.attr('src', fileUrl);
        }
        fider.popup();
    }
</script>

SOURCE/MarketingSystem/MarketingSystem/Views/ServicePlan/_TableServicePlan.cshtml
@using APIProject.Models;
@using Data.Model;
@using Data.Model.APIWeb;
@using Data.Utils
@using PagedList.Mvc
@using System.Web
@model  PagedList.IPagedList<ListServicePlanOutputModel>

<table class="table table-light table-bordered table-hover table-responsive-sm table-responsive mb-0" style=" white-space: nowrap;">
    <thead class="text-center text-white bg-thead">
        <tr>
            <th width="5%">STT</th>
            <th width="30%">Tên gói cước</th>
            <th width="30%">Danh mục</th>
            <th width="20%">Ảnh</th>
            <th width="10%">Trạng thái</th>
            <th width="10%">Giá cước</th>
            <th width="5%">Thời hạn(Tháng)</th>
            <th width="20%">Ngày tạo</th>
            <th width="10%" style=" white-space: nowrap !important;"></th>
        </tr>
    </thead>
    <tbody class="text-center">
        @{
            if (Model.Count() <= 0)
            {
                <tr>
                    <td colspan="9" class="text-center">Không có dữ liệu.</td>
                </tr>
            }
            else
            {


                int stt = ((Model.PageNumber - 1) * Model.PageSize) + 1;
                foreach (var dt in Model)
                {
                    <tr>
                        <td>@stt</td>
                        <td>@dt.Name</td>
                        <td>@dt.CateName</td>
                        <td>
                            <div style="width:100%; height:100%;">
                                <img class="w-100 h-100" src="@dt.ImageUrl" />
                            </div>
                        </td>
                        @{
                            if (dt.Status.Equals(SystemParam.ACTIVE))
                            {
                                <td>Hoạt động</td>

                            }
                            else
                            {
                                <td>Ngừng hoạt động</td>
                            }
                        }
                        <td>@String.Format("{0:n0}", dt.Price)</td>
                        <td>@dt.Value</td>
                        <td>@dt.CreatedDate.ToString(SystemParam.CONVERT_DATETIME)</td>
                        <td>
                            <a data-id="@dt.ID" data-name="@dt.Name" data-value="@dt.Value" data-image="@dt.ImageUrl" data-status="@dt.Status" data-price="@dt.Price" data-descreiption="@dt.Descreiption" data-cateID="@dt.CateID" onclick="GetServicePlanDetail($(this))" data-toggle="tooltip" data-placement="top" title="Cập nhật thông tin gói cước" class="cursor-pointer">
                                <i class="btnEdit fa fa-fw fa-edit"></i>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Xóa gói cước này" class="cursor-pointer" onclick="DelServicePlan(@dt.ID)">
                                <i class="btnDelete fa fa-fw fa-trash-o"></i>
                            </a>
                        </td>
                    </tr>
                    stt++;
                }
            }
        }
    </tbody>
</table>

<div class="col-md-12">
    <div class="row float-right">
        @*phân trang*@
        @Html.PagedListPager(Model, Page => Url.Action("Search", new { Page, searchKey = ViewBag.searchKey, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, status = ViewBag.status, cateID = ViewBag.cateID }),
     PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
     {
         HttpMethod = "GET",
         UpdateTargetId = "tbl-service-plan",
        LoadingElementId = "modalLoad"
     })
     )
    </div>
</div>

@*Modal thêm gói cước*@
<div class="modal fade" id="service-plan-detail" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-white" style="background-color:#1E8449 ">
                <h5 class="modal-title"> <i class="fa fa-plus-square" aria-hidden="true"></i>&nbsp Chi tiết gói cước</h5>
                <button type="button" class="close " style="color:coral" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="frm-edit-service-plan" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Tên gói cước</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <input type="text" name="Name" class="form-control" id="txt-name-edit" placeholder="Nhập tên gói cước..." />
                            <input type="hidden" name="ID" id="val-id" />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Giá gói cước</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <input type="text" class="form-control number" id="txt-price-edit" placeholder="Nhập giá gói cước..." />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Giá trị trong bao nhiêu tháng</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <input type="number" name="Value" onkeydown="javascript: return event.keyCode == 69 || event.keyCode == 189 || event.keyCode == 190 || event.keyCode == 188 ? false : true" class="form-control number" id="value-edit" placeholder="Nhập giá trị..." />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Danh mục</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <select class="form-control" id="cateID-value-edit" name="CateID">
                                @{
                                    foreach (var dt in (List<ListCategoryOutputModel>)ViewBag.listCate)
                                    {
                                        <option value="@dt.ID">@dt.Name</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Trạng thái</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <select class="form-control" id="status-value-edit">
                                <option value="1">Hoạt động</option>
                                <option value="0">Ngưng hoạt động</option>
                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Mô tả</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12">
                            <textarea class="form-control" name="Descreiption" style="height:75px !important" id="txt-description-edit" placeholder="Nhập nội dung mô tả..."></textarea>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-3 col-xs-12 col-sm-12">
                            <strong>Ảnh đại diện</strong>
                        </div>
                        <div class="col-md-9 col-xs-12 col-sm-12 text-center">
                            <a href="" class="text-bold mb-3" style="width:100%;height:100%; color: #5A5A5A;" id="img-edit">
                                <img src="https://cdn4.iconfinder.com/data/icons/social-communication/142/add_photo-512.png" class="col-3" alt="Chọn" />

                            </a>
                            <div class="col-8 offset-2">
                                <div>
                                    <div class="article" id="div-img-edit" style="position:relative">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-success" onclick="UpdateServicePlan()">Cập nhật</button>

            </div>
        </div>

    </div>
</div>

<script>
    $("#img-edit").off('click').on('click', function (e) {
        e.preventDefault();
        var fider = new CKFinder();
        fider.selectActionFunction = function (fileUrl) {
            $("#div-img-edit").empty();
            $("#div-img-edit").append('<div style ="margin-top:10px;"><img id="val-img-edit" class="cursor-pointer" width="100%" height="100%" src="' + fileUrl + '" onclick="ChangeImg($(this));" /></div>');
        }
        fider.popup();
    });

    function ChangeImg($url) {
        var fider = new CKFinder();
        fider.selectActionFunction = function (fileUrl) {
            $url.attr('src', fileUrl);
        }
        fider.popup();
    }
</script>